ci_boost_release.py
Currently this just fills in the new libraries, which is often missed out. In the future will also try to update the version number automatically.
=> Generate root index file using same method as library list

ci_boost_release.py
SaxonHE needs to be setup before use (like other doc tools).
=> Fix documentation build

ci_boost_release.py
It's often a good practice to pin the versions of gems and pip packages, in case a new version unexpectedly breaks something.   
When investigating the pygments.rb gem, it looks like a future version could potentially do this. Better to have "controlled" version upgrades.
=> specify gem versions

download_snaphot.sh
For some reason, there's almost always a missing json file on bintray, so
change `download_snaphot.sh` (sic) so that it continues when that's the case.
It means that there's no check that the release file was correctly downloaded,
so will need to do that manually.
=> Handle missing json files in download_snaphot.sh

ci_boost_common.py, ci_boost_release.py, github_releases.py, github_releases_import.py
Implements github releases using the [gh](https://github.com/cli/cli) tool, which is the official supported github cli. 
- When creating releases locally/manually, install gh. Instructions: https://github.com/cli/cli#installation
- For the CI scripts, add gh to the Docker container. The Docker images have been updated in this pull request https://github.com/boostorg/release-tools/pull/18
There are two alternatives when publishing boost github releases.
1. Add them to https://github.com/boostorg/boost
2. Create a separate repo for releases such as https://github.com/boostorg/boost-releases
The advantage of the first method is that it's expected to find the binaries in the same place as the source. Simple and convenient.
The advantage of the second method is that it's more secure. Access …
=> github releases

ci_boost_release.py, docker/python3/bionic/Dockerfile
Versions of ci_boost_release.py from 2016-2021 were calling http://www.boost.org/doc/generate.php to download and update index.html and libs/libraries.htm in the archive bundles.
If the boost website is being redesigned, generate.php will eventually be deprecated and removed.
It will be convenient to have a self-sufficient release-tool that doesn't depend on the website when building an archive.
The new function generatehtmlpages creates the files index.html and libs/libraries.htm.
I have tested the new generatehtmlpages function, and it is working.  In the event any problems are found, the option to switch back to generate.php is still there.
The first step will be merging into the python3 branch.
=> Replicate generate.php functionality

MakeBoostDistro.py, ci_boost_release.py
The boost-tasks repo from Daniel James included a script release-from-bintray which was used to deploy an archive from bintray to the website. Changing from bintray to artifactory, the "created" timestamp metadata field was used by the earlier script, and should be provided.   To solve that, adding a "created" field to the archive's json file, which is a logical place to store the information, alongside the sha hash and commit.
Another small update also: when running ci_boost_release.py multiple times during testing, the program will crash if the destination folder is present. Let's rename the previous folder to ".bck", and continue to create a new bundle, without crashing.
=> Add "created" field to metadata

ci_boost_release.py
When release-tools creates a boost archive, it downloads ci_boost_common.py and ci_boost_release.py.   Those files are required to build the bundle, but don't need to be included in the final product. This PR excludes them from the zip file.
=> Don't bundle ci_boost_release.py in boost archive

.github/workflows/build_docs.yml, build_docs/README.md, build_docs/compatibility.md, build_docs/linuxdocs.sh, build_docs/macosdocs.sh, build_docs/windowsdocs.ps1
release-tools builds the entire boost release bundle. A task during that process is to compile the documentation. These new build_docs scripts are similar to that. The goal is to compile the documentation for a target library. Thus, more limited and specific. They install prerequisite apt and pip packages, and run b2. Test one target rather than the entire bundle. If someone asks "how do I build the docs for library X", the answer can be "run linuxdocs.sh".
=> Scripts to build docs for specific boost libraries

.github/workflows/build_docs.yml, build_docs/linuxdocs.sh, build_docs/macosdocs.sh, build_docs/windowsdocs.ps1
In the build_docs/ scripts add a flag which causes boost-root to be placed inside the library's folder instead of parallel to it.  The build process is more self-contained.   It could be used by a CI system where a build shouldn't extend beyond it's own directory.
=> build_docs enhancement

build_docs/windowsdocs.ps1
An interesting bug. windowsdocs.ps1 installs windows packages with chocolatey. To use the packages immediately you have to run refreshenv, which updates PATH. However, it can remove path entries as well as add path entries. If it removes the PATH to cl.exe then b2 may fail to build. So, after running refreshenv, put back the previous PATH entries.
=> windowsdocs.ps1 refreshenv

.github/workflows/build_docs.yml, build_docs/macosdocs.sh
This update doesn't affect releases.  
- Modify Github Actions CI file, improve data collection of the "build_docs" scripts, which are building individual libraries.
- Add cxxstd for MacOS, because newer versions of boost are dropping cxxstd 03 support.
=> Update builddocs github actions CI

ci_boost_release.py, docker/README.md, docker/python3/focal/Dockerfile, docker/python3/focal/buildrelease.sh
Adds a new function `upload_to_s3` in ci_boost_release.py.  For a limited and specific purpose. Documentation is hosted on the boost.org website at these URLs:
https://www.boost.org/doc/libs/develop/
https://www.boost.org/doc/libs/master/
Those are folders "develop" and "master" on the webserver.   In the new website, those sets of files should also be uploaded somewhere, and hosted by the website.  `upload_to_s3` does that.  The files will be in extracted format, not a zipped archive.
=> Sync to S3

ci_boost_common.py, ci_boost_release.py, docker/python3/focal/Dockerfile
This commit adds support for libraries with Antora documentation. In this workflow, each library can be an Antora component in an Antora master project hosted in another repository (https://github.com/cppalliance/site-docs) which also includes extra components with the user guide, contributor guide, and a component about the review process. At a later step, the antora documentation is merged with the existing in-source documentation generated with other tools.
=> Support Antora documentation

publish_release.py
Slowly working on formatting the files in release-tools. This is for `publish_release.py`.
"""
Black is the uncompromising Python code formatter. By using it, you agree to cede control over minutiae of hand-formatting. In return, Black gives you speed, determinism, and freedom from pycodestyle nagging about formatting. You will save time and mental energy for more important matters.
Blackened code looks the same regardless of the project you're reading. Formatting becomes transparent after a while and you can focus on the content instead.
Black makes code review faster by producing the smallest diffs possible.
"""
=> Lint publish_release.py with the python code formatter Black

.github/workflows/ci.yml, publish_release.py
Adds a GitHub Actions CI step to check on code formatting.  Doesn't change files, just displays pass/fail information.
=> CI: code formatter

ci_boost_release.py
Changes the release script to only patch `libs` with directories from the Antora documentation. 
This means `libs` won't be patched with files from the Antora build dir, such as `404.html`, `robots.txt`, and `sitemap.xml`, as these are the responsibility of the boost website. Antora also used to generate and need a `search-index.js` file but that's been already removed in https://github.com/cppalliance/site-docs/commit/fc1bd3962203f673877ea08d3b010a6034afbbf6.
The only problem left is `_` in `libs`. We're discussing a solution to that.
Related to #57.
=> Patch Antora directories only

.gitignore, publish_release.py
The boost downloads are hosted on an additional site `archives.boost.io` which is a Fastly CDN.   `brorigin1.cpp.al` and `brorigin2.cpp.al` are the origin servers.  After running `publish-release.py` upload a list of new files to "/tmp/boostarchivesinfo/filelist.txt".  This informs the origin servers that they should download the new files from jfrog, or wherever they are available.  The files would be downloaded anyway, but it's on a 1-day schedule, so the purpose of this feature is to speed up the process.
=> publish_release.py: inform CDN origins about new archive files

publish_release.py
Jfrog is deprecated.  Here are other options:  
- only rely on brorigin1, brorigin2 to store the files. Or,  
- replace jfrog with an S3 bucket
AWS S3 is 10x cheaper than the most basic JFrog subscription. It adds a level of redundancy to safely keep a copy of the downloads.  
Created S3 bucket "boost-archives". 
Enabled versioning.
This pull request adds the feature to be able to upload archive bundles to S3 from `publish_release.py`. 
When approaching the Jfrog end-of-life, change the various dryrun settings to enable S3 uploads, and also switch the "s3 website docs" dryrun setting so that it's based on the right variable.     
In the meantime, archives should still be uploaded to S3. That's being done on brorigin1 in a cron, and so at the moment isn't needed in `publish_release.py`.
=> publish_release.py: upload archives to s3

publish_release.py
JFrog and Fastly currently have the same boost snapshots, so it doesn't matter which ones `publish_release.py` downloads.  In the future, JFrog will become unavailable.   Download snapshots from Fastly.
=> publish_release.py downloads snapshots from Fastly

build_docs/linuxdocs.sh, build_docs/macosdocs.sh, build_docs/windowsdocs.ps1
build_docs:  
- Switch from cp to rsync, fixing an error
- Display final results more clearly
- Install newer ruby version on macos. Add to PATH
=> build_docs updates

ci_boost_release.py
When switching to ubuntu 24.04, 7z started crashing 
```
*** buffer overflow detected ***: terminated
```
This pull request restricts the number of threads.
```
-mmt2
```
=> Set 7z threads to 2

ci_boost_release.py
This speeds up the build process by allowing Antora extensions to use this path to find the Boost source files needed to generate the reference pages.
=> Set BOOST_SRC environment variable

docker/python3/noble/Dockerfile, docker/python3/noble/buildimage.sh
Usually the boost build runs as `root`.  For external CI jobs that are testing documentation builds (not in circleci), it's helpful to allow a regular user (named jenkins) to sudo and install packages in a container.    This does not affect the usual workflow which continues to use `root`.
=> docker: jenkins user for CI

publish_release.py
Includes the 'git tag' commands in `publish_release.py`.  
This is a step closer to having `publish_release.py` take care of everything in the release.
It's opt-in with the --git-tag flag.  Otherwise nothing changes, and tagging can be done manually as before.
=> publish_release: git tagging procedure

ci_boost_release.py
Antora documentation builds require that a directory is a git repository. To facilitate this when building the docs during the release process, we introduce a convention of `doc/antora_docs.sh` which the release script uses to convert the git submodule in `/root/project/libs` to a proper git repository that can work with Antora. From there, it's up to each library's `doc/Jamfile.v2` to generate its own docs properly.
=> update release script to convert submodules to repositories

ci_boost_common.py, ci_boost_release.py
When other developers contribute to `release-tools` they may not know about the method: pip/gem packages are maintained in the Dockerfiles.     
`ci_boost_release.py` can be misleading, containing multiple "install" functions, which are quite out-of-date, with the wrong versions.  
- Remove some install functions.  
- Add comments.
Don't merge this pull request until after the next boost release.
=> Remove some package install functions

publish_release.py
Before, the error checking in `publish_release.py` attempted to log in to boost.io.   
Now, setting that to try both stage.boost.org and boost.org.
=> publish_release.py: extend preflight check to staging website also
